projects:
  appsynctodo:
    schemaPath: src/graphql/schema.json
    includes:
      - src/graphql/**/*.js
    excludes:
      - ./amplify/**
    extensions:
      amplify:
        codeGenTarget: javascript
        generatedFileName: ''
        docsFilePath: src/graphql
        graphQLApiId: lurrjhnbwnaxdabkogoxntek64
      endpoints:
        prod: >-
          https://r4il6g54f5gflovwyot2wjsnie.appsync-api.ap-northeast-1.amazonaws.com/graphql
